/**
 * The wordmark renderer, pinned against Python's.
 *
 * `WORDMARK_SAMPLES` is `render_ascii_text()` output generated by
 * `scripts/gen_web_types.py`, so this is a genuine cross-language check rather
 * than two implementations agreeing with their own separate expectations. That
 * distinction is not academic here: the join-code wire format shipped broken
 * with a green test on each side, because each side asserted the contract it
 * had assumed. One generated artifact, both readers.
 */

import { render, screen } from '@testing-library/preact';
import { describe, expect, it } from 'vitest';

import { BLOCK_GLYPHS, SHADOW_GLYPHS, SHADOW_SAMPLES, WORDMARK_SAMPLES } from '../../types/enums';
import { renderShadowWordmark, renderWordmark, Wordmark } from './Wordmark';

describe('renderWordmark', () => {
  it.each(Object.keys(WORDMARK_SAMPLES))('matches render_ascii_text for %j', (word) => {
    expect(renderWordmark(word)).toEqual([...(WORDMARK_SAMPLES[word] as readonly [string, string])]);
  });

  it('is case-insensitive — the glyph table is uppercase only', () => {
    expect(renderWordmark('retro')).toEqual(renderWordmark('RETRO'));
  });

  it('replaces an unknown character with a gap, keeping the rows aligned', () => {
    // Dropping it instead would shift every later letter on one row only.
    const [top, bottom] = renderWordmark('a/a');
    expect(top.length).toBe(bottom.length);
    // "A" plus its separator is four cells, then the three-cell gap.
    expect(top.slice(4, 7)).toBe('   ');
    expect(bottom.slice(4, 7)).toBe('   ');
  });

  it('renders both rows to the same width for every known glyph', () => {
    // A glyph whose rows differ in width would shear the whole word after it.
    for (const [ch, [top, bottom]] of Object.entries(BLOCK_GLYPHS)) {
      expect(top.length, `glyph ${ch} rows differ in width`).toBe(bottom.length);
    }
  });
});

describe('renderShadowWordmark', () => {
  it.each(Object.keys(SHADOW_SAMPLES))('matches render_shadow_text for %j', (word) => {
    const want = SHADOW_SAMPLES[word];
    expect(renderShadowWordmark(word)).toEqual(want === null ? null : [...(want ?? [])]);
  });

  it('kerns — this is the part a naive port gets wrong', () => {
    // "analysis" is in the samples for exactly this reason: its L and Y nest by
    // three columns. Concatenation reproduces every other sample byte-for-byte
    // and only widens this one, so without an explicit assertion a broken fit()
    // would look almost entirely correct.
    const widths = [...'ANALYSIS'].reduce((n, ch) => n + (SHADOW_GLYPHS[ch]?.[0]?.length ?? 0), 0);
    expect(renderShadowWordmark('analysis')?.[0]?.length).toBe(widths - 3);
  });

  it('does not kern a space away', () => {
    // The space glyph is all blanks, so it nests into anything — the gap between
    // two words would vanish entirely without the guard.
    const gap =
      (renderShadowWordmark('a a')?.[0]?.length ?? 0) - (renderShadowWordmark('aa')?.[0]?.length ?? 0);
    expect(gap).toBe(SHADOW_GLYPHS[' ']?.[0]?.length);
  });

  it('returns null for a word the face cannot set, rather than a damaged one', () => {
    expect(renderShadowWordmark('sprint 42')).toBeNull();
    expect(renderShadowWordmark('n/a')).toBeNull();
  });

  it('renders every row of a word to the same width', () => {
    const rows = renderShadowWordmark('roadmap') ?? [];
    expect(rows).toHaveLength(6);
    expect(new Set(rows.map((r) => r.length)).size).toBe(1);
  });

  it('holds six rows of one width for every glyph', () => {
    for (const [ch, glyph] of Object.entries(SHADOW_GLYPHS)) {
      expect(glyph.length, `glyph ${ch} is not six rows`).toBe(6);
      expect(new Set(glyph.map((r) => r.length)).size, `glyph ${ch} rows differ in width`).toBe(1);
    }
  });
});

describe('<Wordmark variant="shadow">', () => {
  it('sets the word in the tall face', () => {
    const { container } = render(<Wordmark text="retro" variant="shadow" />);
    expect(container.querySelector('pre')?.textContent).toBe(
      (SHADOW_SAMPLES['retro'] as readonly string[]).join('\n'),
    );
  });

  it('still announces the word and not the block characters', () => {
    render(<Wordmark text="retro" variant="shadow" />);
    expect(screen.getByRole('img', { name: 'retro' })).toBeTruthy();
  });

  it('falls back to the compact face when the word has no setting', () => {
    // An export picking a wordmark with a digit in it must degrade to the small
    // face, not to a blank masthead.
    const { container } = render(<Wordmark text="sprint 42" variant="shadow" />);
    // The compact face is drawn rather than typeset, so what proves the
    // fallback is an svg carrying the word — not a `<pre>` of six rows.
    expect(container.querySelector('pre')).toBeNull();
    const svg = container.querySelector('svg');
    expect(svg?.getAttribute('aria-label')).toBe('sprint 42');
    expect(svg?.querySelector('path')?.getAttribute('d')).toBeTruthy();
  });

  it('wraps itself in a query container so the size can be derived', () => {
    // The face is a fixed cell grid, so a 60-cell word only fits a phone if the
    // size comes from the space available; a static font-size would mean a
    // horizontal scrollbar under the hero on every narrow screen.
    //
    // Only the container is asserted here. The size itself is an inline
    // `min(…, calc(100cqi …))`, and jsdom's CSS parser rejects `cqi` outright and
    // drops the whole declaration — so the computed value is a browser check
    // (`make dev-board` at 375px), not one this file can make.
    const { container } = render(<Wordmark text="standup" variant="shadow" />);
    const wrapper = container.querySelector('span');
    expect(wrapper?.className).toBeTruthy();
    expect(wrapper?.querySelector('pre')).toBeTruthy();
  });

  it('lets an explicit size win over the derived one', () => {
    const { container } = render(<Wordmark text="retro" variant="shadow" size="8px" />);
    expect(container.querySelector('pre')?.getAttribute('style')).toContain('8px');
  });
});

describe('<Wordmark>', () => {
  it('exposes the word, not the block characters, to assistive tech', () => {
    render(<Wordmark text="retro" />);
    // Without this the screen reader announces a run of U+2588s.
    expect(screen.getByRole('img', { name: 'retro' })).toBeTruthy();
  });

  it('takes an explicit label when the word is not the whole message', () => {
    render(<Wordmark text="retro" label="Sprint retrospective" />);
    expect(screen.getByRole('img', { name: 'Sprint retrospective' })).toBeTruthy();
  });

  it('draws the compact face as one path, not a grid of characters', () => {
    // The block characters were the seam: a <pre> renders one glyph per cell,
    // so every letter boundary showed a hairline the accent could not cover.
    // Merged rectangles in a single path have no boundaries to show.
    const { container } = render(<Wordmark text="retro" />);
    expect(container.querySelector('pre')).toBeNull();
    const path = container.querySelector('svg path');
    expect(path?.getAttribute('d')).toMatch(/^M/);
    expect(container.textContent).not.toContain('█');
  });

  it('sizes the viewBox to the glyph grid, shades blanked', () => {
    const { container } = render(<Wordmark text="yeaboi" />);
    const rows = WORDMARK_SAMPLES['yeaboi'] as readonly [string, string];
    // Two character rows, four pixel rows: `▀` and `▄` are half cells, so each
    // row of the face is two rows of the bitmap. `░` is the font's background
    // cell — dim in a terminal, nothing at all here, so it is simply not drawn.
    expect(container.querySelector('svg')?.getAttribute('viewBox')).toBe(`0 0 ${rows[0].length} 4`);
  });
});
