/**
 * The exported-report shell.
 *
 * The theme case is the one with history behind it. The old shell's switcher
 * was an `onclick="__yeaboiCycleTheme()"` string in a page with no runtime, and
 * the storage key it wrote is a **compatibility contract**: a report someone
 * exported last month, sitting on their disk, reads that exact key. So the
 * picker changed shape but must not change where it writes.
 */

import { render, screen } from '@testing-library/preact';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it } from 'vitest';

import { THEME_KEYS } from '../runtime/theme';
import type { ExportChrome } from './boot';
import { Shell } from './Shell';

function chrome(over: Partial<ExportChrome> = {}): ExportChrome {
  return {
    mode: 'planning',
    frame: 'yeaboi — planning',
    wordmark: 'roadmap',
    title: 'Roadmap — Q3 2026',
    footer: 'Generated by yeaboi.ai • 2026-07-30',
    ...over,
  };
}

beforeEach(() => {
  localStorage.clear();
  document.documentElement.removeAttribute('data-theme');
});

describe('Shell', () => {
  it('sets the report title as the only h1', () => {
    render(
      <Shell chrome={chrome()} theme="midnight">
        <p>body</p>
      </Shell>
    );
    expect(screen.getAllByRole('heading', { level: 1 }).map((h) => h.textContent)).toEqual(['Roadmap — Q3 2026']);
  });

  it('labels the wordmark, because the glyphs are geometry to a screen reader', () => {
    render(
      <Shell chrome={chrome()} theme="midnight">
        <p>body</p>
      </Shell>
    );
    expect(screen.getByRole('img', { name: 'roadmap' })).toBeTruthy();
  });

  it('renders each header fact as a labelled eyebrow', () => {
    const { container } = render(
      <Shell chrome={chrome({ facts: [['SOURCE', 'local'], ['ANALYZED', '2026-07-20']] })} theme="midnight">
        <p>body</p>
      </Shell>
    );
    expect(container.textContent).toContain('SOURCE');
    expect(container.textContent).toContain('local');
    expect(container.textContent).toContain('ANALYZED');
  });

  it('shows contents links only when there is more than a screen to navigate', () => {
    const { container, rerender } = render(
      <Shell chrome={chrome()} theme="midnight">
        <p>body</p>
      </Shell>
    );
    expect(container.querySelector('nav')).toBeNull();

    rerender(
      <Shell chrome={chrome({ nav: [['projects', 'Projects']] })} theme="midnight">
        <p>body</p>
      </Shell>
    );
    expect(screen.getByRole('link', { name: 'Projects' }).getAttribute('href')).toBe('#projects');
  });

  it('persists a theme change under the key old exports already read', async () => {
    const user = userEvent.setup();
    render(
      <Shell chrome={chrome()} theme="midnight">
        <p>body</p>
      </Shell>
    );

    await user.click(screen.getByRole('radio', { name: 'forest' }));
    expect(document.documentElement.getAttribute('data-theme')).toBe('forest');
    expect(localStorage.getItem(THEME_KEYS.export)).toBe('forest');
  });

  it('opens on the palette the document was already painted with', () => {
    render(
      <Shell chrome={chrome()} theme="solarized">
        <p>body</p>
      </Shell>
    );
    expect(screen.getByRole('radio', { name: 'solarized' }).getAttribute('aria-checked')).toBe('true');
  });

  it('renders the report body', () => {
    render(
      <Shell chrome={chrome()} theme="midnight">
        <p>the report</p>
      </Shell>
    );
    expect(screen.getByText('the report')).toBeTruthy();
  });
});
