/**
 * The deck's persistent furniture: where you are, and how to move.
 *
 * All mono, all `--dim`, all sitting on the edges — a projected slide should be
 * the content and a thin frame that tells a latecomer what they are looking at.
 * The progress indicator is a flat accent rule rather than the two-stop
 * gradient it replaced: a gradient on a 4px bar reads as a smear at the back of
 * a room, and it was the only place in the deck that used one.
 */

import { Duck, Wordmark, type DuckState } from '../design/primitives';
import styles from './deck.module.css';

export interface ControlsProps {
  index: number;
  total: number;
  onPrev: () => void;
  onNext: () => void;
  onTheme: () => void;
  /** Name of the palette the T key will switch to — the button's tooltip. */
  nextThemeName: string;
}

export function Controls({ index, total, onPrev, onNext, onTheme, nextThemeName }: ControlsProps) {
  const progress = total > 1 ? (index / (total - 1)) * 100 : 100;
  return (
    <div className={styles['chrome']}>
      <div className={styles['progress']}>
        <div className={styles['bar']} style={{ width: `${progress}%` }} />
      </div>
      <div className={styles['controls']}>
        <button type="button" onClick={onPrev} disabled={index === 0} aria-label="Previous slide">
          ‹
        </button>
        {/* Not aria-live: the slide itself is announced, and a screen reader
            reading "4 / 11" on top of every slide change is pure noise. */}
        <span className={styles['counter']}>
          {index + 1} / {total}
        </span>
        <button type="button" onClick={onNext} disabled={index >= total - 1} aria-label="Next slide">
          ›
        </button>
        <button type="button" onClick={onTheme} title={`Cycle theme (T) — next: ${nextThemeName}`}>
          ◑
        </button>
      </div>
      <p className={styles['hint']}>← / → or Space to navigate · T for theme · F fullscreen</p>
    </div>
  );
}

/**
 * The credit line: the duck, the product's own block-glyph mark, and the date.
 *
 * The duck used to arrive as a 44 KB base64 PNG that Python inlined into every
 * exported deck. It comes from the bundle now — the same quantised 128px
 * sprites the boards use, ~7 KB for all three layers — so the deck is smaller
 * for having gained an animated mascot.
 */
export function Brand({ generated, duck }: { generated: string; duck: DuckState }) {
  return (
    <div className={styles['brand']}>
      <Duck state={duck} size={26} />
      <span className={styles['brandMark']}>
        Generated by <Wordmark text="yeaboi" label="yeaboi.ai" size="5px" className={styles['brandWordmark']} />
        <span aria-hidden="true">.ai</span>
      </span>
      <span className={styles['brandDate']}>{generated}</span>
    </div>
  );
}
