/**
 * Accessibility smoke test over the whole shared library.
 *
 * Every component gets rendered and run through axe. This is deliberately a
 * *floor*, not a substitute for the specific assertions in the behaviour tests
 * beside it — axe catches missing names, bad roles and colour-independent
 * structure problems; it cannot tell you that Escape closes the right panel or
 * that focus goes back to the trigger.
 *
 * It is worth having because the boards it replaces had, measurably: no dialog
 * semantics anywhere, no `aria-expanded` on any popover, and icon-only buttons
 * whose only label was a `title`.
 */

import { render } from '@testing-library/preact';
import { describe, expect, it } from 'vitest';
import { axe } from 'vitest-axe';

import {
  Avatar,
  Card,
  Chip,
  DataTable,
  Legend,
  NoticeBlock,
  Prose,
  ProseBullets,
  RichText,
  Section,
  SegmentBar,
  Sparkline,
  StatBar,
  StatGrid,
  StatTile,
} from '../design/primitives';
import { IconButton } from './IconButton';
import { InviteQR } from './InviteQR';
import { JoinGate } from './JoinGate';
import { MusicPlayer } from './MusicPlayer';
import { PageShell } from './PageShell';
import { Popover, PopoverGroup } from './Popover';
import { PresenceRow, Roster, TypingIndicator } from './Presence';
import { ThemeSwitcher } from './ThemeSwitcher';
import { TimerControls, TimerReadout } from './Timer';
import { Toolbar } from './Toolbar';
import { Visualizer } from './Visualizer';

const noop = (): void => {};

const music = {
  playing: false,
  connecting: false,
  analyser: null,
  channel: 0,
  volume: 0.35,
  toggle: noop,
  play: async () => {},
  stop: noop,
  setChannel: noop,
  setVolume: noop,
  cast: async () => {},
};

const people = [
  { name: 'Alice Johnson', avatar: '🦊' },
  { name: 'Bob', avatar: '🐢' },
];

/**
 * Every component, rendered in a representative state.
 *
 * A table rather than a test per component so adding one to the library and
 * forgetting to add it here is visible as a missing row, not as silence.
 */
const CASES: [name: string, node: preact.ComponentChildren][] = [
  ['Chip', <Chip tone="ok">shipped</Chip>],
  ['Chip (link)', <Chip href="https://jira.example/AB-1">AB-1</Chip>],
  [
    'StatGrid',
    <StatGrid>
      <StatTile value="42" label="Story points" hint="up 8 from last sprint" />
    </StatGrid>,
  ],
  ['StatBar', <StatBar pct={72} label="capacity 29 of 40 points" />],
  [
    'SegmentBar',
    <SegmentBar
      label="work by source: github 12, jira 5"
      segments={[
        { value: 12, tone: 'accent' },
        { value: 5, tone: 'info' },
      ]}
    />,
  ],
  [
    'Legend',
    <Legend
      items={[
        { label: 'github', tone: 'accent', count: 12 },
        { label: 'jira', tone: 'info', count: 5 },
      ]}
    />,
  ],
  [
    'Sparkline',
    <Sparkline values={[3, 5, 4, 8, 7]} title="velocity, last 5 sprints" startLabel="Apr" endLabel="Aug" />,
  ],
  ['Avatar', <Avatar name="Alice Johnson" />],
  ['NoticeBlock', <NoticeBlock title="Caveats" items={['Only 3 days of data.']} />],
  ['Card', <Card title="Sprint 12">Body text.</Card>],
  ['Section', <Section title="Delivery">Body text.</Section>],
  [
    'DataTable',
    <DataTable
      caption="Points per member"
      rows={[{ name: 'Alice', points: 8 }]}
      columns={[
        { key: 'name', header: 'Member', cell: (r) => r.name },
        { key: 'points', header: 'Points', numeric: true, cell: (r) => r.points },
      ]}
      rowKey={(r) => r.name}
    />,
  ],
  ['Prose', <Prose text={'Line one.\nLine two.'} />],
  ['ProseBullets', <ProseBullets text="Shipped the API. Docs are behind; tests are green." />],
  ['RichText', <RichText runs={[{ s: 'See ' }, { s: 'AB-1', href: 'https://jira.example/AB-1' }]} />],
  ['IconButton', <IconButton icon="🔒" label="Lock the board" />],
  ['InviteQR', <InviteQR qrSrc="/api/qr?token=x" joinCode="K3P9-2QXA" inviteUrl="https://x.trycloudflare.com/#code=K3P9-2QXA" />],
  ['JoinGate', <JoinGate />],
  ['MusicPlayer', <MusicPlayer music={music} channels={[{ name: 'Lofi', url: 'https://example/stream' }]} />],
  [
    'Popover',
    <PopoverGroup>
      <Popover label="Music" trigger={<span aria-hidden="true">♪</span>}>
        <p>panel</p>
      </Popover>
    </PopoverGroup>,
  ],
  [
    'PageShell',
    // The component that introduces the landmark structure the rest of this
    // list sits inside: an <h1>, a <main>, and a contentinfo that must stay
    // outside it. Rendered in the app variant, where the footer moves into the
    // shell's region and so is the rendition most likely to nest it wrongly.
    <PageShell
      chrome={{
        mode: 'retro',
        frame: 'yeaboi — retro',
        wordmark: 'retro',
        title: 'Sprint Retro',
        subtitle: 'Sprint 42',
        facts: [['PROJECT', 'yeaboi']],
        footer: 'Generated by yeaboi.ai',
      }}
      variant="app"
      density="hero"
      bar={<Toolbar subtitle="12 cards" tools={<IconButton icon="🔒" label="Lock" />} />}
    >
      <p>board</p>
    </PageShell>,
  ],
  ['PresenceRow', <PresenceRow people={people} />],
  ['Roster', <Roster people={people} meName="Bob" />],
  ['TypingIndicator', <TypingIndicator names={['Alice Johnson']} />],
  ['ThemeSwitcher', <ThemeSwitcher value="midnight" onChange={noop} />],
  ['TimerReadout', <TimerReadout remaining={95} />],
  ['TimerControls', <TimerControls running onStart={noop} onStop={noop} />],
  ['Toolbar', <Toolbar brand="Sprint Retro" subtitle="12 cards" tools={<IconButton icon="🔒" label="Lock" />} />],
  ['Visualizer', <Visualizer playing />],
];

describe('axe', () => {
  it.each(CASES)('%s has no violations', async (_name, node) => {
    const { container } = render(<>{node}</>);
    expect(await axe(container)).toHaveNoViolations();
  });
});
