/**
 * The byline link.
 *
 * Small surface, but two of its three attributes are load-bearing rather than
 * decorative, and both fail silently: `target="_blank"` protects a live board
 * and a half-typed share code from a same-tab navigation, and `rel` closes the
 * `window.opener` hole that `target="_blank"` opens.
 *
 * The URL itself is pinned in `tests/unit/test_web_assets.py`, which blanks
 * exactly this literal before scanning the bundles for external references.
 * Changing it here without changing it there fails the build.
 */

import { render, screen } from '@testing-library/preact';
import { describe, expect, it } from 'vitest';

import { Credit, CREDIT_URL } from './Credit';

describe('Credit', () => {
  it('links the byline to the project site', () => {
    render(<Credit>Generated by yeaboi.ai</Credit>);
    const link = screen.getByRole('link', { name: 'Generated by yeaboi.ai' });
    expect(link.getAttribute('href')).toBe(CREDIT_URL);
  });

  it('opens in a new tab so a live board is never navigated away from', () => {
    render(<Credit>Generated by yeaboi.ai</Credit>);
    expect(screen.getByRole('link').getAttribute('target')).toBe('_blank');
  });

  it('closes the opener hole that target="_blank" opens', () => {
    render(<Credit>Generated by yeaboi.ai</Credit>);
    const rel = screen.getByRole('link').getAttribute('rel') ?? '';
    expect(rel).toContain('noopener');
    expect(rel).toContain('noreferrer');
  });

  it('keeps a caller class, which is how the deck corner keeps its own colour', () => {
    render(<Credit className="corner-hash">yeaboi.ai</Credit>);
    expect(screen.getByRole('link').className).toContain('corner-hash');
  });
});
