/**
 * The `Generated by yeaboi.ai` byline, as a link to the project.
 *
 * Every surface wears this string — the export masthead's footer, the two live
 * boards, the share gate under its card, the deck's corner credit — and until
 * now every one of them rendered it as inert text. The reason was
 * `test_bundle_fetches_nothing`, which greps the minified bundles for an
 * external URL because it cannot tell an `<a href>` from a `fetch()` once
 * esbuild has been through them.
 *
 * That test is right about what it protects and wrong about this case, so the
 * test now blanks this one literal before it scans. **A link is a place to go,
 * not something the page loads**: an export opened over `file://` with no
 * network renders byte-identically with or without it, and the tunnel CSPs
 * govern fetches and framing, not where a click takes you. A second occurrence
 * of the URL — an `<img src>`, a font, an actual fetch — still fails the guard.
 *
 * `target="_blank"`, and that part is not a preference. Three of the four
 * surfaces are *live*: leaving a retro board, a poker round or a half-typed
 * share code to read the marketing site would cost the visitor their seat in
 * the room. On an export it is merely polite.
 */

import type { ReactNode } from 'react';

import { cx } from '../runtime/cx';
import styles from './shared.module.css';

/** The one external URL any bundle is allowed to contain. */
export const CREDIT_URL = 'https://yeaboi.ai';

export interface CreditProps {
  children: ReactNode;
  className?: string | undefined;
}

export function Credit({ children, className }: CreditProps) {
  return (
    <a
      className={cx(styles['credit'], className)}
      href={CREDIT_URL}
      target="_blank"
      // `noreferrer` implies `noopener`, but both are spelled out: the implication
      // holds in current browsers and not in the older ones a tunnel link reaches.
      rel="noopener noreferrer"
    >
      {children}
    </a>
  );
}
