/**
 * The masthead every surface now wears.
 *
 * The density switch is the part worth pinning. `test/setup.ts` stubs
 * `matchMedia` to `matches: false` for every suite, so without an explicit
 * override here *every* board test renders the compact rendition and the hero
 * one — the whole point of the change — is executed by nothing.
 */

import { render, screen, within } from '@testing-library/preact';
import { afterEach, describe, expect, it } from 'vitest';

import type { PageChrome } from './chrome';
import { PageShell } from './PageShell';

const CHROME: PageChrome = {
  mode: 'retro',
  frame: 'yeaboi — retro',
  wordmark: 'retro',
  title: 'Sprint Retro',
  // Deliberately not the same string as any fact value, so `getByText` below
  // distinguishes "the subtitle rendered" from "the facts row rendered".
  subtitle: 'the sprint 42 retrospective',
  facts: [
    ['PROJECT', 'yeaboi'],
    ['SPRINT', 'Sprint 42'],
  ],
  badges: ['beta'],
  footer: 'Generated by yeaboi.ai',
};

/** Force the hero query on or off, whatever the shared setup stub says. */
function setRoomy(roomy: boolean): () => void {
  const original = window.matchMedia;
  window.matchMedia = ((query: string) => ({
    matches: roomy,
    media: query,
    addEventListener: () => {},
    removeEventListener: () => {},
    addListener: () => {},
    removeListener: () => {},
  })) as unknown as typeof window.matchMedia;
  return () => void (window.matchMedia = original);
}

describe('PageShell', () => {
  let restore: (() => void) | null = null;
  afterEach(() => {
    restore?.();
    restore = null;
  });

  it('renders the chrome a document surface carries', () => {
    render(
      <PageShell chrome={CHROME}>
        <p>body</p>
      </PageShell>
    );

    expect(screen.getByRole('heading', { level: 1 }).textContent).toBe('Sprint Retro');
    expect(screen.getByText('the sprint 42 retrospective')).toBeTruthy();
    expect(screen.getByText('yeaboi — retro')).toBeTruthy();
    expect(screen.getByText('Generated by yeaboi.ai')).toBeTruthy();
    expect(screen.getByText('body')).toBeTruthy();
  });

  it('keeps the credit out of the main landmark', () => {
    // contentinfo inside main is a landmark violation.
    render(
      <PageShell chrome={CHROME}>
        <p>report</p>
      </PageShell>
    );

    const main = screen.getByRole('main');
    expect(within(main).queryByText('Generated by yeaboi.ai')).toBeNull();
    expect(screen.getByText('Generated by yeaboi.ai')).toBeTruthy();
  });

  it('gives a board no footer at all', () => {
    // A board's screen is finite and every row of it is the board.
    render(
      <PageShell chrome={CHROME} variant="app">
        <p>board</p>
      </PageShell>
    );

    expect(screen.queryByText('Generated by yeaboi.ai')).toBeNull();
    expect(screen.queryByRole('contentinfo')).toBeNull();
  });

  it('wears the terminal window on a document and not on a board', () => {
    // The frame title is the only text TerminalFrame renders, so it stands in
    // for the whole window.
    const { unmount } = render(
      <PageShell chrome={CHROME}>
        <p>report</p>
      </PageShell>
    );
    expect(screen.getByText('yeaboi — retro')).toBeTruthy();
    unmount();

    render(
      <PageShell chrome={CHROME} variant="app">
        <p>board</p>
      </PageShell>
    );
    expect(screen.queryByText('yeaboi — retro')).toBeNull();
    // …and the identity it used to carry is still on the page.
    expect(screen.getByRole('heading', { level: 1 }).textContent).toBe('Sprint Retro');
  });

  describe('density', () => {
    it('shows the subtitle and the facts row when the viewport can pay for it', () => {
      render(
        <PageShell chrome={CHROME} variant="app" density="hero">
          <p>board</p>
        </PageShell>
      );

      expect(screen.getByText('the sprint 42 retrospective')).toBeTruthy();
      expect(screen.getByText('PROJECT')).toBeTruthy();
      expect(screen.getByText('beta')).toBeTruthy();
    });

    it('drops them when it cannot', () => {
      // Compact keeps the wordmark and the title and sheds the rest.
      render(
        <PageShell chrome={CHROME} variant="app" density="compact">
          <p>board</p>
        </PageShell>
      );

      expect(screen.queryByText('PROJECT')).toBeNull();
      expect(screen.queryByText('beta')).toBeNull();
      // The identity itself stays — that is the difference between compact and
      // no masthead at all.
      expect(screen.getByRole('heading', { level: 1 }).textContent).toBe('Sprint Retro');
    });

    it('an app surface is compact regardless of the viewport', () => {
      // Its screen does not scroll, so no window is big enough for a 260px
      // header.
      restore = setRoomy(true);
      render(
        <PageShell chrome={CHROME} variant="app">
          <p>board</p>
        </PageShell>
      );
      expect(screen.queryByText('PROJECT')).toBeNull();
      expect(screen.queryByText('the sprint 42 retrospective')).toBeNull();
    });

    it("resolves an explicit 'auto' from the viewport", () => {
      restore = setRoomy(true);
      const { unmount } = render(
        <PageShell chrome={CHROME} variant="app" density="auto">
          <p>board</p>
        </PageShell>
      );
      expect(screen.getByText('PROJECT')).toBeTruthy();
      unmount();

      restore();
      restore = setRoomy(false);
      render(
        <PageShell chrome={CHROME} variant="app" density="auto">
          <p>board</p>
        </PageShell>
      );
      expect(screen.queryByText('PROJECT')).toBeNull();
    });

    it('a document surface is hero regardless of the viewport', () => {
      // An export is a document — it does not get to be compact because the
      // window happens to be small, and printing it must not depend on it.
      restore = setRoomy(false);
      render(
        <PageShell chrome={CHROME}>
          <p>report</p>
        </PageShell>
      );
      expect(screen.getByText('PROJECT')).toBeTruthy();
    });
  });

  it('renders the contents nav only when there is one', () => {
    const { unmount } = render(
      <PageShell chrome={CHROME}>
        <p>report</p>
      </PageShell>
    );
    expect(screen.queryByRole('navigation', { name: 'Contents' })).toBeNull();
    unmount();

    render(
      <PageShell chrome={{ ...CHROME, nav: [['team', 'Team']] }}>
        <p>report</p>
      </PageShell>
    );
    const nav = screen.getByRole('navigation', { name: 'Contents' });
    expect(within(nav).getByText('Team').getAttribute('href')).toBe('#team');
  });

  it('passes data attributes through to the root', () => {
    // poker's console keys several rules off [data-host] on this element; if it
    // stops arriving the deck's last row hides behind the host's bottom sheet.
    const { container } = render(
      <PageShell chrome={CHROME} variant="app" data={{ 'data-host': 'true' }}>
        <p>board</p>
      </PageShell>
    );
    expect(container.querySelector('[data-host="true"]')).toBeTruthy();
  });

  it('places the bar between the masthead and the content', () => {
    const { container } = render(
      <PageShell chrome={CHROME} variant="app" bar={<div data-testid="bar">toolbar</div>}>
        <p>board</p>
      </PageShell>
    );

    // The masthead's title, not the frame title: a board renders no frame, and
    // indexOf would return -1 and pass without asserting anything.
    const html = container.innerHTML;
    expect(html.indexOf('Sprint Retro')).toBeLessThan(html.indexOf('toolbar'));
    expect(html.indexOf('toolbar')).toBeLessThan(html.indexOf('board'));
  });
});
