// @vitest-environment node
//
// Reads files off disk, so it needs Node rather than the suite's jsdom default.

/**
 * Guards on the committed duck sprites.
 *
 * The mascot layers are generated by the yeaboi repo's `gen_duck_sprites.py`
 * from the website's master art and committed here, because Pillow lives only
 * in that repo's `charts` extra and no build in this one may depend on it.
 * Committed generated binaries need a guard, and these are the three failures
 * that would actually happen:
 *
 * - a layer goes missing, so the duck loses its sunglasses in production only;
 * - a layer is regenerated at a different size, so the composite shears — the
 *   three are stacked with `position: absolute; inset: 0` and nothing at
 *   runtime would complain;
 * - someone drops the full-resolution art back in, quietly adding ~265 KB of
 *   base64 to every board *and* to each of the ten exported report files.
 *
 * Dimensions come straight out of the PNG header, so this needs no image
 * library. Ported from the yeaboi repo's `tests/unit/test_web_duck_sprites.py`.
 */

import { readFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const SPRITE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'duck');
const LAYERS = ['base', 'wing', 'glasses'] as const;

/**
 * The three layers are inlined as data: URIs into every self-contained page.
 * base64 costs a third on top, so this ceiling is ~13 KB on the wire. The
 * current total is ~5.4 KB; the headroom is for a re-cut, not for the 199 KB
 * original.
 */
const MAX_TOTAL_BYTES = 10 * 1024;

const spritePath = (layer: string) => join(SPRITE_DIR, `${layer}.png`);

/**
 * Width and height from a PNG's IHDR chunk. The header is fixed-layout: an
 * 8-byte signature, a 4-byte length, the `IHDR` tag, then two big-endian
 * uint32s.
 */
function pngSize(path: string): [number, number] {
  const header = readFileSync(path).subarray(0, 24);
  expect(header.subarray(0, 8).toString('latin1'), `${path} is not a PNG`).toBe(
    '\x89PNG\r\n\x1a\n',
  );
  return [header.readUInt32BE(16), header.readUInt32BE(20)];
}

describe('duck sprites', () => {
  it('has every layer', () => {
    const missing = LAYERS.filter((layer) => {
      try {
        statSync(spritePath(layer));
        return false;
      } catch {
        return true;
      }
    });
    expect(missing, "run the yeaboi repo's scripts/gen_duck_sprites.py").toEqual([]);
  });

  it('draws all three at one geometry', () => {
    // They are stacked with `inset: 0`, so a layer even one pixel off puts the
    // sunglasses on the duck's forehead — and it would look merely *odd*
    // rather than broken, which is exactly the kind of thing that ships.
    const sizes = LAYERS.map((layer) => pngSize(spritePath(layer)).join('x'));
    expect(new Set(sizes).size, `duck layers disagree on size: ${sizes.join(', ')}`).toBe(1);
  });

  it('ships a 2x sprite', () => {
    // 128px wide, twice the 64px the rig draws it at.
    expect(pngSize(spritePath('base'))[0]).toBe(128);
  });

  it('stays small enough to inline', () => {
    const total = LAYERS.reduce((sum, layer) => sum + statSync(spritePath(layer)).size, 0);
    expect(
      total,
      `duck sprites total ${(total / 1024).toFixed(1)} KB, over the ${MAX_TOTAL_BYTES / 1024} KB budget — ` +
        're-run gen_duck_sprites.py rather than committing the source art',
    ).toBeLessThanOrEqual(MAX_TOTAL_BYTES);
  });
});
